import Link from 'next/link';
import type { ReactNode } from 'react';
import { demoSequences } from '@/data/demo-sequences';

const contents = [
  ['quick-start', 'Quick start'], ['input', 'Sequence input'], ['levels', 'Prediction levels'],
  ['pathways', 'Phase 3 classes'], ['ec', 'Phase 4 outputs'], ['results', 'Reading results'],
  ['structures', 'Protein structures'], ['motifs', 'Motifs and database links'],
  ['example', 'Worked example'], ['standalone', 'Standalone usage'],
  ['troubleshooting', 'Troubleshooting'], ['privacy', 'Privacy and retention'],
  ['limitations', 'Interpretation and limitations'], ['citation', 'Citation and support'],
];
const routes = [
  {name:'Anammox', description:'Anaerobic ammonium oxidation.', ec:['1.7.2.7','1.7.2.8'], learned:true},
  {name:'Assimilatory', description:'Nitrogen transformations associated with incorporation into cellular material.', ec:['1.4.1.13-14+1.4.7.1','1.4.1.2','1.4.1.3','1.4.1.4','1.7.1.1-3+1.7.7.2','1.7.1.4','1.7.7.1','6.3.1.2'], learned:true},
  {name:'Denitrification', description:'Reduction steps associated with gaseous nitrogen products.', ec:['1.7.2.4','1.7.2.5'], learned:true},
  {name:'Denitrification / nitrification', description:'A shared functional class associated with both named pathways.', ec:['1.7.2.1'], learned:false},
  {name:'Dissimilatory', description:'Nitrogen reduction associated with energy metabolism rather than incorporation into biomass.', ec:['1.7.1.15','1.7.2.2'], learned:true},
  {name:'Dissimilatory / denitrification', description:'A shared functional class associated with dissimilatory reduction and denitrification.', ec:['1.9.6.1'], learned:false},
  {name:'Dissimilatory / denitrification / nitrification', description:'A shared functional class associated with all three named contexts.', ec:['1.7.5.1'], learned:false},
  {name:'Hydroxylamine reduction', description:'Reduction of hydroxylamine.', ec:['1.7.99.1'], learned:false},
  {name:'Nitrification', description:'Oxidative transformations associated with nitrification.', ec:['1.14.99.39','1.7.2.6'], learned:true},
  {name:'Nitrogen fixation', description:'Reduction of molecular nitrogen to ammonia.', ec:['1.18.6.1'], learned:false},
];
function Section({id,title,children}:{id:string;title:string;children:ReactNode}) {
  return <section id={id} className="surface scroll-mt-28 p-6 sm:p-8"><h2 className="mb-4 text-2xl font-semibold text-[var(--navy)]">{title}</h2><div className="space-y-4 text-base leading-7 text-slate-700">{children}</div></section>;
}
function Code({children}:{children:ReactNode}) {return <pre className="overflow-x-auto rounded-lg border border-[var(--line)] bg-slate-50 p-4 font-mono text-sm leading-6">{children}</pre>;}
export default function Help() {
  const example = demoSequences.all.trim().split(/\n(?=>)/)[0];
  return <div className="space-y-8 py-5 sm:py-8">
    <header className="rounded-2xl bg-[var(--navy)] px-6 py-8 text-white sm:px-9"><p className="text-sm font-medium text-[#9fccef]">User guide</p><h1 className="mt-2 text-4xl font-semibold">Using DeepNEC 2.0</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-200">Prepare sequences, choose a prediction level, and interpret enzyme, pathway, EC, motif, and structure results.</p></header>
    <div className="grid items-start gap-7 lg:grid-cols-[230px_minmax(0,1fr)]">
      <aside className="surface p-5 lg:sticky lg:top-24"><nav aria-label="Help contents"><h2 className="mb-3 font-semibold text-[var(--navy)]">On this page</h2><ol className="space-y-2 text-sm leading-6">{contents.map(([id,label])=><li key={id}><a className="block rounded px-2 py-1 text-[var(--blue)] hover:bg-slate-50 focus-visible:outline-2" href={'#'+id}>{label}</a></li>)}</ol></nav><Link href="/prediction" className="btn-primary mt-5 w-full">Start prediction</Link></aside>
      <div className="min-w-0 space-y-6">
        <Section id="quick-start" title="Quick start">
          <ol className="list-decimal space-y-2 pl-6"><li>Open <Link className="underline" href="/prediction">Prediction</Link> and choose Protein or Nucleotide.</li><li>Paste FASTA, upload a file, or retrieve protein accessions. Use Load example to try the supplied protein sequences.</li><li>Select Phase 1, 2, 3, or 4. For the complete hierarchy, choose Phase 4 and Automatic.</li><li>Complete verification, then select Start prediction. Queueing and processing time depend on server load and input size.</li><li>Save the complete private results link. Review the phase tables and download your results.</li></ol>
        </Section>
        <Section id="input" title="Sequence input">
          <h3 className="font-semibold">Protein FASTA</h3><p>Each record begins with &gt; followed by an identifier, then its sequence on one or more lines. Use a unique first word in every header; descriptions after a space are not part of the identifier. Do not paste alignment gaps, residue numbers, or stop symbols.</p>
          <p>The web form accepts the 20 standard amino acids and X, in upper or lower case. X residues are removed before prediction. Protein U, O, B, Z, J, gaps, and * are not accepted by the web form; review the underlying sequence rather than silently substituting uncertain residues.</p>
          <h3 className="font-semibold">Nucleotide FASTA</h3><p>Select Nucleotide before submitting DNA or RNA FASTA. The accepted alphabet is A, C, G, T, U and N. TransDecoder extracts open reading frames and translates them before classification. Results refer to predicted proteins, not directly to the submitted nucleotide records; one record may yield multiple ORFs or none. Short or incomplete transcripts may not yield an ORF. The deployed backend must have TransDecoder available.</p>
          <h3 className="font-semibold">Accessions and examples</h3><p>Choose UniProtKB or NCBI Protein under Accession, enter protein identifiers, and select Retrieve sequences. Review the returned FASTA before submission. Accession retrieval and Load example switch the form to protein input. Invalid, unavailable, or nucleotide-only accessions cannot be retrieved through the protein lookup.</p>
          <h3 className="font-semibold">Request limits</h3><p>The deployment defaults below can be changed by the server administrator. If the live form reports a different limit, follow that message. Limits apply together, not independently.</p>
          <dl className="grid grid-cols-[1fr_auto] gap-x-5 gap-y-2 text-sm"><dt>Sequences per request</dt><dd>10,000</dd><dt>Total residues or nucleotide bases</dt><dd>50,000,000</dd><dt>Residues or bases per sequence</dt><dd>5,000</dd><dt>Protein accessions per lookup</dt><dd>100</dd><dt>Accession length</dt><dd>64 characters</dd><dt>Request body</dt><dd>64 MiB</dd><dt>Active jobs per client</dt><dd>2</dd></dl>
          <p>For large datasets, we recommend the <Link className="underline" href="/download">standalone tool</Link> on your computer or cluster.</p>
        </Section>
        <Section id="levels" title="The four prediction levels">
          <dl className="space-y-4"><div><dt className="font-semibold">Phase 1 — Enzyme filter</dt><dd>Classifies submitted proteins as Enzyme or Non-enzyme. Only predicted enzymes continue.</dd></div><div><dt className="font-semibold">Phase 2 — Nitrogen filter</dt><dd>Classifies those enzymes as Nitrogen or Non-nitrogen, meaning nitrogen-metabolism or non-nitrogen-metabolism enzymes. Only the Nitrogen group continues.</dd></div><div><dt className="font-semibold">Phase 3 — Pathway classification</dt><dd>Assigns each remaining protein to one of the ten classes below.</dd></div><div><dt className="font-semibold">Phase 4 — EC assignment</dt><dd>Assigns an EC-level output within that protein’s Phase 3 route, using a learned classifier or a direct mapping.</dd></div></dl>
          <p>Selecting a level runs the preceding gates and stops at that level. A Phase 4 request does not guarantee a Phase 4 row for every submitted sequence. If no proteins pass a gate, later phases may have no table.</p>
        </Section>
        <Section id="pathways" title="Phase 3: ten pathway classes">
          <p>Combined names denote one shared class, not several independently predicted labels. They do not establish that the source organism carries a complete pathway or operates all of these processes.</p>
          <details open><summary className="cursor-pointer font-semibold text-[var(--blue)]">View pathway definitions</summary><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm leading-6"><caption className="sr-only">The ten deployed Phase 3 classes</caption><thead className="bg-slate-50"><tr><th scope="col" className="p-3">Class</th><th scope="col" className="p-3">Meaning</th></tr></thead><tbody className="divide-y divide-[var(--line)]">{routes.map(r=><tr key={r.name}><th scope="row" className="p-3 align-top font-medium">{r.name}</th><td className="p-3 align-top">{r.description}</td></tr>)}</tbody></table></div></details>
          <p>Table headings abbreviate Anammox as Anam., Assimilatory as Assim., Dissimilatory as Diss., Denitrification as Den., Nitrification as Nit., Hydroxylamine reduction as HA red., and Nitrogen fixation as N fix. Slashes join combined pathway names. Downloaded files retain the original machine-readable labels, including underscores.</p>
        </Section>
        <Section id="ec" title="Phase 4: EC outputs and routing">
          <p>The current hierarchy reports 21 terminal outputs spanning 26 EC annotations: 16 outputs from five learned classifiers and five direct mappings. It is not a predictor for every EC number.</p>
          <details open><summary className="cursor-pointer font-semibold text-[var(--blue)]">View all routes and EC outputs</summary><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm leading-6"><caption className="sr-only">Phase 3 parents and deployed Phase 4 outputs</caption><thead className="bg-slate-50"><tr><th scope="col" className="p-3">Phase 3 parent</th><th scope="col" className="p-3">Assignment</th><th scope="col" className="p-3">EC outputs</th></tr></thead><tbody className="divide-y divide-[var(--line)]">{routes.map(r=><tr key={r.name}><th scope="row" className="p-3 align-top font-medium">{r.name}</th><td className="p-3 align-top">{r.learned?'Learned classifier':'Direct mapping'}</td><td className="p-3 align-top"><ul className="space-y-1">{r.ec.map(ec=><li key={ec}>{ec}</li>)}</ul></td></tr>)}</tbody></table></div></details>
          <h3 className="font-semibold">Consolidated outputs</h3><p>1.4.1.13-14+1.4.7.1 represents EC 1.4.1.13, 1.4.1.14 and 1.4.7.1. Similarly, 1.7.1.1-3+1.7.7.2 represents EC 1.7.1.1, 1.7.1.2, 1.7.1.3 and 1.7.7.2. Each group is one model output; it does not resolve an individual member or imply that one protein performs every listed activity.</p>
          <h3 className="font-semibold">Automatic or selected pathway</h3><p>Automatic uses the Phase 3 route for each protein. Selecting one pathway limits Phase 4 processing to proteins that Phase 3 assigns to that pathway. It does not bypass the earlier gates or force other proteins into the selected route. If none match, there may be no Phase 4 output.</p>
          <p>A direct mapping assigns the single EC associated with its Phase 3 class. It is not an additional independently evaluated classifier; a deterministic assignment should not be interpreted as 100% biological certainty.</p>
        </Section>
        <Section id="results" title="Reading and downloading results">
          <dl className="space-y-3"><div><dt className="font-semibold">Sequence ID</dt><dd>The protein identifier used to join rows across phases. Nucleotide submissions use translated ORF identifiers.</dd></div><div><dt className="font-semibold">Prediction / Pathway / EC</dt><dd>The selected class for that phase. A missing downstream row usually means the protein did not pass an earlier gate or did not match the selected pathway.</dd></div><div><dt className="font-semibold">Class percentages</dt><dd>Softmax scores displayed as percentages for the classes within that task. They are not experimentally verified confidence estimates. Scores from different phases or different Phase 4 classifiers are not interchangeable. Blue, teal, and amber highlights mark the highest, second, and third scores within each row. Tied displayed scores share a rank, with subsequent ranks skipped. Colors represent relative ranking, not calibrated confidence.</dd></div><div><dt className="font-semibold">Structure</dt><dd>Predict or view secondary and 3D structure for a protein. These optional requests do not change its enzyme or EC prediction.</dd></div></dl>
          <p>Choose a phase tab, then TSV, CSV, or JSON to download that table. TSV is tab-delimited; CSV opens in spreadsheet software; JSON is convenient for scripts. Exports retain the original field names and values. Keep identifiers intact when joining tables.</p>
          <p>The number of rows normally decreases through the hierarchy. This is filtering, not necessarily missing data. Compare each protein’s earlier phase result before interpreting an absent EC assignment.</p>
        </Section>
        <Section id="structures" title="Secondary and 3D structures">
          <h3 className="font-semibold">Secondary structure — S4PRED</h3><p>Select Predict secondary in the results table. The page opens the viewer after prediction finishes. AA is the amino-acid sequence, Pred is the residue assignment, Cart is its graphical representation, and Conf is the predictor’s per-residue confidence score from 0 (low) to 9 (high). H denotes helix, E strand, and C coil. Hover over residues for details. Download the prediction text or export the graphic as PNG or SVG.</p>
          <h3 className="font-semibold">Tertiary structure — ESMFold or SWISS-MODEL</h3><p>The current implementation tries ESMFold for proteins up to 400 residues. Longer proteins use SWISS-MODEL; when configured, SWISS-MODEL also provides a fallback if ESMFold is unavailable. SWISS-MODEL uses template-based modelling and may need additional queueing and processing time. A suitable model is not guaranteed.</p>
          <p>Select Predict 3D once. The table shows progress and opens the viewer when coordinates are ready. SWISS-MODEL checks reuse the saved project rather than starting a fresh submission. If you leave and return, use the structure button to resume checking. Completed structures are reused for the same sequence within the same prediction job, including across phase tabs.</p>
          <p>In the 3D viewer, drag to rotate and scroll or pinch to zoom. Change the representation, color scheme, or background, highlight supported motifs, or reset the view. Download PDB coordinates for other molecular viewers; PNG and SVG export the displayed view. The SVG contains a rendered image rather than editable molecular geometry.</p>
          <p>These are predicted structures, not experimental measurements. Coordinate availability does not establish correct folding, enzyme activity, ligand binding, or pathway membership. Model coverage and quality can vary. Browser WebGL support is required for the interactive 3D display.</p>
        </Section>
        <Section id="motifs" title="Motifs and external database links">
          <p>The Motifs table counts sequence-pattern matches for Rossmann Fold, NADP Basic, NAD Acidic, Ferredoxin FeS, Mo MGD Binding, Heme Binding CXXCH, and Iron Sulfur CxxC. These are heuristic pattern names, not confirmed domains or cofactor assignments. Zero means no match to that pattern; a nonzero count alone does not establish function. Motif counts are supplemental annotations, not inputs to the deployed ESM-2 classifiers.</p>
          <p>Phase 4 links open searches for the EC label in NCBI Protein, UniProt, BRENDA, KEGG, and JGI. They help you inspect reference annotations and related records; they are not evidence that your submitted protein is already present or experimentally characterized in those databases. For a consolidated label, search its individual EC members separately if the combined query is not recognized.</p>
        </Section>
        <Section id="example" title="Worked example">
          <p>On the Prediction page, choose Phase 4 and Automatic, then Load example. The supplied multi-record FASTA starts with AEQ03576.1. Its complete sequence is shown below directly from the website’s example data.</p><Code>{example}</Code>
          <ol className="list-decimal space-y-2 pl-6"><li>Submit the supplied example and save the result link.</li><li>Locate AEQ03576.1 in Phase 1. If it is classified as Enzyme, look for the same ID in Phase 2.</li><li>If Phase 2 labels it Nitrogen, read its Phase 3 pathway. Then inspect its Phase 4 EC output and the relevant class scores.</li><li>Select Predict secondary or Predict 3D in its row. Return to the table using Back to results table.</li><li>Download each phase table you need. Use Sequence ID to follow this protein across them.</li></ol><p>This walkthrough describes how to read a run, not a promised label or score. Use the output of the installed model version rather than treating demo sequences as independent validation evidence.</p>
        </Section>
        <Section id="standalone" title="Standalone usage">
          <p>For large datasets, we recommend using the <Link className="underline" href="/download">standalone tool</Link> on your computer or cluster. Installation and the source archive are on the Download page.</p><h3 className="font-semibold">Protein FASTA</h3><Code>deepnec -i proteins.fasta -od results -l Phase4 -t prot</Code><h3 className="font-semibold">Nucleotide FASTA</h3><Code>deepnec -i transcripts.fasta -od results -l Phase4 -t nucl</Code><p>Nucleotide processing requires TransDecoder.LongOrfs on PATH. The translated_proteins.fasta file contains the predicted ORFs used for classification. Use Phase1, Phase2, or Phase3 in place of Phase4 to stop earlier. Run deepnec --help for the options supported by your installed version.</p>
        </Section>
        <Section id="troubleshooting" title="Troubleshooting">
          {[
            ['Invalid FASTA or unsupported character','Check that every record has a header and sequence, the correct input type is selected, and the alphabet matches the input rules above. Remove alignment formatting and use unique identifiers.'],
            ['Verification is missing or expired','Allow the verification widget to load and complete it before submission. Refresh if it expires. A configuration error requires administrator assistance.'],
            ['Request too large or too many jobs','Split the input into smaller batches, wait for existing jobs to finish, or use the standalone tool. All size limits apply together.'],
            ['No downstream table or EC result','Review Phase 1 and Phase 2 filters and the selected Phase 4 pathway. A protein rejected earlier is not classified at later depths.'],
            ['No translated proteins','Check the nucleotide sequence and transcript length. TransDecoder may find no suitable ORF; backend installation errors require administrator assistance.'],
            ['Structure prediction is taking time','Keep the page open for automatic checks. A queued SWISS-MODEL project is not a failed model. After returning to the result link, select the structure control to resume checks.'],
            ['ESMFold 504, SWISS-MODEL failure, or structure request error','The external service may be unavailable, rate-limited, or unable to generate a model. Check again later; a saved SWISS-MODEL project is reused. A confirmed FAILED project may require support. Classification results remain available even if structure prediction fails.'],
            ['Blank 3D viewer','Check browser WebGL support or try another browser. You can download the PDB and inspect it in a local molecular viewer.'],
            ['Results unavailable','Use the complete original bookmark, including the fragment after #. The link may be incomplete, expired, or belong to a different deployment. A job ID alone does not grant access.'],
            ['Cluster submission or server configuration error','Contact support with the job ID, time, selected level, and exact error text. Do not repeatedly submit the same input while a service problem is unresolved.'],
          ].map(([title,body])=><details key={title} className="border-b border-[var(--line)] pb-3"><summary className="cursor-pointer font-semibold text-[var(--navy)]">{title}</summary><p className="mt-2">{body}</p></details>)}
        </Section>
        <Section id="privacy" title="Privacy and result retention">
          <p>Anyone with the complete result link can access that job. Keep the link private; do not post it in public issue reports. Download results before the displayed availability date. The default retention period is 30 days, but administrators can configure it.</p>
          <p>Classification runs on the configured compute backend. Requesting tertiary structure sends that protein sequence to ESMFold or SWISS-MODEL. Do not request external structure prediction for confidential sequences unless you are authorized to share them with those services. Their retention and privacy policies are separate from DeepNEC’s local job retention.</p>
        </Section>
        <Section id="limitations" title="Interpretation and limitations">
          <p>DeepNEC predicts sequence-based functional labels; it does not measure enzyme activity, expression, reaction direction, metabolic flux, or the completeness of an organism’s nitrogen pathways. Its coverage is limited to the documented classes. An unfamiliar or out-of-scope protein can still receive a high score.</p><p>Each later phase depends on earlier routing. Accuracy for a pathway-conditioned classifier is not the same as accuracy for the complete hierarchy. Short fragments, ambiguous residues, ORF errors, and sequences unlike the training data can affect predictions. Long proteins are subject to the embedding model’s length handling; accepting a sequence does not guarantee that every residue contributes to the classifier representation.</p><p>Interpret predictions together with sequence quality, reference annotations, homology, genomic context, and experimental evidence where available.</p>
        </Section>
        <Section id="citation" title="Citation, reproducibility, and support">
          <p>When reporting an analysis, identify DeepNEC 2.0, the webserver URL, access date, selected prediction level and pathway, and input type. For standalone runs, also record the software revision and model version. Keep the downloaded result tables with your analysis.</p>
          <p>For the appropriate publication citation or technical assistance, contact <a className="underline" href="mailto:naveen.duhan@usu.edu">Naveen Duhan</a>. Report software issues through the <a className="underline" href="https://github.com/usubioinfo/deepnec-2.0-web/issues">webserver issue tracker</a> or <a className="underline" href="https://github.com/usubioinfo/deepnec-2.0/issues">standalone issue tracker</a>. Include the error message and version, but exclude private result tokens, credentials, and confidential sequences.</p>
        </Section>
      </div>
    </div>
  </div>;
}
